// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXR53KmBVo6WEV7cOMnurcsFNocG6c8zM',
    appId: '1:866724920702:web:42c228ed69daf38578872f',
    messagingSenderId: '866724920702',
    projectId: 'notesapp-ea64a',
    authDomain: 'notesapp-ea64a.firebaseapp.com',
    storageBucket: 'notesapp-ea64a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqKOFkR45izWQ9Ujuv05f3d3nuj76eAU0',
    appId: '1:866724920702:android:07dfa3322d8d37b878872f',
    messagingSenderId: '866724920702',
    projectId: 'notesapp-ea64a',
    storageBucket: 'notesapp-ea64a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPwnlscfPlPH1C1j0RlSoXOJtMtCwMok',
    appId: '1:866724920702:ios:fac98e26a993a34b78872f',
    messagingSenderId: '866724920702',
    projectId: 'notesapp-ea64a',
    storageBucket: 'notesapp-ea64a.appspot.com',
    iosBundleId: 'com.akapps.akNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPwnlscfPlPH1C1j0RlSoXOJtMtCwMok',
    appId: '1:866724920702:ios:fac98e26a993a34b78872f',
    messagingSenderId: '866724920702',
    projectId: 'notesapp-ea64a',
    storageBucket: 'notesapp-ea64a.appspot.com',
    iosBundleId: 'com.akapps.akNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXR53KmBVo6WEV7cOMnurcsFNocG6c8zM',
    appId: '1:866724920702:web:0a1a3c2c584b548578872f',
    messagingSenderId: '866724920702',
    projectId: 'notesapp-ea64a',
    authDomain: 'notesapp-ea64a.firebaseapp.com',
    storageBucket: 'notesapp-ea64a.appspot.com',
  );
}
